@extends('admin.layouts.app')

@section('header')
    {{ $project->exists ? __('admin.edit_project') . ': ' . ($project->name_ar ?? $project->name_en) : __('admin.create_new') }}
@endsection

@section('content')
<div class="bg-white shadow rounded-lg p-6">
    <!-- Step Indicator -->
    <div class="mb-6">
        <h2 class="text-xl font-bold text-gray-800">{{ __('admin.project_wizard.step_basics') }}</h2>
        <p class="text-sm text-gray-500">{{ __('admin.project_wizard.step_1_of_x') }}</p>
        <div class="mt-2 h-2 bg-gray-200 rounded-full">
            <div class="h-2 bg-indigo-600 rounded-full" style="width: 15%"></div>
        </div>
    </div>

    <form action="{{ route('admin.projects.steps.basics.store', $project->id) }}" method="POST" id="basics-form">
        @csrf

        {{-- Note: Inputs are now generated by the x-location.map component (lat, lng, boundary_geojson) --}}
        {{-- However, Project Wizard uses custom logic to bind these. --}}
        {{-- We let the component generate inputs: 'lat', 'lng', 'boundary_geojson'. --}}
        {{-- We still need to make sure the form submits them. --}}

        <div class="space-y-6">
            <!-- Project Name (Arabic) -->
            <div>
                <label for="name_ar" class="block text-sm font-semibold text-gray-700">
                    {{ __('admin.project_wizard.name_ar') }} <span class="text-red-500">*</span>
                </label>
                <input
                    type="text"
                    id="name_ar"
                    name="name_ar"
                    value="{{ old('name_ar', $project->name_ar ?? '') }}"
                    class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                    placeholder="{{ __('admin.project_wizard.name_ar_placeholder') }}"
                    required
                >
                @error('name_ar')
                    <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                @enderror
            </div>

            <!-- Project Name (English) -->
            <div>
                <label for="name_en" class="block text-sm font-semibold text-gray-700">
                    {{ __('admin.project_wizard.name_en') }} <span class="text-red-500">*</span>
                </label>
                <input
                    type="text"
                    id="name_en"
                    name="name_en"
                    value="{{ old('name_en', $project->name_en ?? '') }}"
                    class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                    placeholder="{{ __('admin.project_wizard.name_en_placeholder') }}"
                    required
                >
                @error('name_en')
                    <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                @enderror
            </div>

            <!-- Launch Date Row -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <!-- Launch Date -->
                <div>
                    <label for="launch_date" class="block text-sm font-semibold text-gray-700">
                        {{ __('admin.project_wizard.launch_date_label') }}
                    </label>
                    <input
                        type="date"
                        id="launch_date"
                        name="launch_date"
                        value="{{ old('launch_date', isset($project->launch_date) ? $project->launch_date->format('Y-m-d') : '') }}"
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                        placeholder="{{ __('admin.project_wizard.launch_date_placeholder') }}"
                    >
                    @error('launch_date')
                        <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                    @enderror
                </div>

                <!-- Empty Column for Layout -->
                <div class="hidden md:block">
                    <!-- Placeholder to preserve 2-column layout -->
                </div>
            </div>

            <!-- Developer -->
            <div>
                <label for="developer_id" class="block text-sm font-semibold text-gray-700">
                    {{ __('admin.project_wizard.developer') }} <span class="text-red-500">*</span>
                </label>
                <x-developers.select
                    name="developer_id"
                    :selected-id="old('developer_id', $project->developer_id)"
                />
                @error('developer_id')
                    <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                @enderror
            </div>

            <!-- PROJECT LOCATION SECTION -->
            <div class="pt-6 border-t border-gray-200">
                <h3 class="text-lg font-medium text-gray-900 mb-4">{{ __('admin.project_wizard.location_section_unified') }}</h3>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <input
                        type="hidden"
                        id="country_id"
                        name="country_id"
                        value="{{ old('country_id', $project->country_id ?? $defaultCountry->id ?? '') }}"
                    >
                    <div class="md:col-span-2">
                        <div class="flex items-center justify-between">
                            <label class="block text-sm font-semibold text-gray-700">
                                {{ __('admin.country') }}
                            </label>
                            <span class="text-xs text-gray-500">{{ app()->getLocale() === 'ar' ? 'مخفي ومثبت على الدولة الافتراضية' : 'Hidden and fixed to the default country' }}</span>
                        </div>
                        <p class="mt-1 text-sm text-gray-600">{{ $defaultCountry?->name_local ?? $defaultCountry?->name_en }}</p>
                    </div>

                    <!-- Region / Governorate -->
                    <div>
                        <label for="region_id" class="block text-sm font-semibold text-gray-700">
                            {{ __('admin.region') }} <span class="text-red-500">*</span>
                        </label>
                        <select
                            id="region_id"
                            name="region_id"
                            data-selected="{{ old('region_id', $project->region_id) }}"
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                            required
                        >
                            <option value="">{{ __('admin.select_option') }}</option>
                            @foreach($regions as $region)
                                <option
                                    value="{{ $region->id }}"
                                    data-lat="{{ $region->lat }}"
                                    data-lng="{{ $region->lng }}"
                                    {{ (old('region_id', $project->region_id) == $region->id) ? 'selected' : '' }}
                                >
                                    {{ $region->name_local ?? $region->name_en }}
                                </option>
                            @endforeach
                        </select>
                        @error('region_id')
                            <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                        @enderror
                    </div>

                    <!-- City -->
                    <div>
                        <label for="city_id" class="block text-sm font-semibold text-gray-700">
                            {{ __('admin.city') }} <span class="text-red-500">*</span>
                        </label>
                        <select
                            id="city_id"
                            name="city_id"
                            data-selected="{{ old('city_id', $project->city_id) }}"
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                            required
                        >
                            <option value="">{{ __('admin.select_option') }}</option>
                            @foreach($cities as $city)
                                <option
                                    value="{{ $city->id }}"
                                    data-lat="{{ $city->lat }}"
                                    data-lng="{{ $city->lng }}"
                                    {{ (old('city_id', $project->city_id) == $city->id) ? 'selected' : '' }}
                                >
                                    {{ $city->name_local ?? $city->name_en }}
                                </option>
                            @endforeach
                        </select>
                        @error('city_id')
                            <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                        @enderror
                    </div>

                    <!-- District -->
                    <div>
                        <label for="district_id" class="block text-sm font-semibold text-gray-700">
                            {{ __('admin.district') }} <span class="text-gray-500 text-xs">({{ __('admin.optional') }})</span>
                        </label>
                        <select
                            id="district_id"
                            name="district_id"
                            data-selected="{{ old('district_id', $project->district_id) }}"
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                        >
                            <option value="">{{ __('admin.select_option') }}</option>
                            @foreach($districts as $district)
                                <option
                                    value="{{ $district->id }}"
                                    data-lat="{{ $district->lat }}"
                                    data-lng="{{ $district->lng }}"
                                    {{ (old('district_id', $project->district_id) == $district->id) ? 'selected' : '' }}
                                >
                                    {{ $district->name_local ?? $district->name_en }}
                                </option>
                            @endforeach
                        </select>
                        @error('district_id')
                            <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
            </div>

            <!-- MAP SECTION -->
            <div class="pt-6 border-t border-gray-200">
                <h3 class="text-lg font-medium text-gray-900 mb-4">{{ __('admin.project_map_unified') }}</h3>
                <p class="text-sm text-gray-500 mb-2">{{ __('admin.project_map_instruction') }}</p>

                <x-location.map
                    :lat="$project->lat ?? 26.8206"
                    :lng="$project->lng ?? 30.8025"
                    :polygon="$project->boundary_geojson"
                    mapId="map-container"
                    entityLevel="project"
                    :entityId="$project->id"
                    :lockToEgypt="false"
                    inputLatName="lat"
                    inputLngName="lng"
                    inputPolygonName="boundary_geojson"
                    :autoInit="false"
                />
            </div>

        </div>

        <!-- Navigation Buttons -->
        <div class="mt-8 flex justify-between">
            <button
                type="button"
                class="px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 opacity-50 cursor-not-allowed"
                disabled
            >
                {{ __('admin.previous') }}
            </button>
            <button
                type="submit"
                class="px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
                {{ __('admin.next') }}
            </button>
        </div>
    </form>
</div>

@push('scripts')
    {{-- location-map scripts are included by the component if not already --}}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // --- CASCADING DROPDOWNS ---
            const countrySelect = document.getElementById('country_id');
            const regionSelect = document.getElementById('region_id');
            const citySelect = document.getElementById('city_id');
            const districtSelect = document.getElementById('district_id');

            const locale = "{{ app()->getLocale() }}"; // 'ar' or 'en'
            let mapInstance;
            let selectedBoundaryLayer;

            function resetSelect(select, placeholder) {
                select.innerHTML = placeholder;
                select.disabled = true;
            }

            function populateSelect(select, items, selectedId = null) {
                const placeholder = '<option value="">{{ __('admin.select_option') }}</option>';
                resetSelect(select, placeholder);
                if (!items || !items.length) {
                    return;
                }

                items.forEach(item => {
                    const option = document.createElement('option');
                    option.value = item.id;
                    option.text = locale === 'ar' ? (item.name_local || item.name_en) : item.name_en;
                    if(item.lat && item.lng) {
                        option.dataset.lat = item.lat;
                        option.dataset.lng = item.lng;
                    }
                    if (selectedId && String(selectedId) === String(item.id)) {
                        option.selected = true;
                    }
                    select.appendChild(option);
                });
                select.disabled = false;
            }

            function flyToLocation(lat, lng, zoom) {
                if(mapInstance && lat && lng) {
                    mapInstance.flyTo([lat, lng], zoom);
                }
            }

            function fetchAndRenderBoundary(level, id) {
                if (!level || !id || !mapInstance) {
                    renderBoundary(null);
                    return;
                }

                const url = new URL(`{{ url('admin/location-polygons') }}`);
                url.searchParams.set('level', level);
                url.searchParams.set('id', id);

                fetch(url)
                    .then(response => response.json())
                    .then(data => {
                        const key = level + 's';
                        const collection = data[key] || [];
                        const match = collection.find(item => String(item.id) === String(id));
                        renderBoundary(match ? match.polygon : null);
                    })
                    .catch(() => renderBoundary(null));
            }

            function renderBoundary(geojson) {
                const boundaryInput = document.getElementById('boundary-map-container');
                if (selectedBoundaryLayer && mapInstance) {
                    mapInstance.removeLayer(selectedBoundaryLayer);
                    selectedBoundaryLayer = null;
                }

                if (!geojson || !mapInstance) {
                    if (boundaryInput) boundaryInput.value = '';
                    return;
                }

                const feature = geojson.type === 'FeatureCollection'
                    ? geojson
                    : { type: 'FeatureCollection', features: [{ type: 'Feature', geometry: geojson, properties: {} }] };

                selectedBoundaryLayer = L.geoJSON(feature, {
                    style: {
                        color: '#2563eb',
                        weight: 3,
                        opacity: 0.8,
                        fillOpacity: 0.1,
                    }
                }).addTo(mapInstance);

                if (selectedBoundaryLayer.getBounds && selectedBoundaryLayer.getBounds().isValid()) {
                    mapInstance.fitBounds(selectedBoundaryLayer.getBounds(), { maxZoom: 15 });
                }

                if (boundaryInput) {
                    boundaryInput.value = JSON.stringify(feature);
                }
            }

            function handleBoundaryUpdate() {
                const districtId = districtSelect.value;
                const cityId = citySelect.value;
                const regionId = regionSelect.value;

                if (districtId) {
                    fetchAndRenderBoundary('district', districtId);
                } else if (cityId) {
                    fetchAndRenderBoundary('city', cityId);
                } else if (regionId) {
                    fetchAndRenderBoundary('region', regionId);
                } else {
                    renderBoundary(null);
                }
            }

            function loadRegions(countryId, selectedRegionId = null, selectedCityId = null, selectedDistrictId = null) {
                resetSelect(regionSelect, '<option value="">{{ __('admin.select_option') }}</option>');
                resetSelect(citySelect, '<option value="">{{ __('admin.select_option') }}</option>');
                resetSelect(districtSelect, '<option value="">{{ __('admin.select_option') }}</option>');

                if (!countryId) return;

                fetch(`{{ url('admin/locations/regions') }}/${countryId}`)
                    .then(response => response.json())
                    .then(data => {
                        populateSelect(regionSelect, data.regions, selectedRegionId);
                        if (selectedRegionId) {
                            loadCities(selectedRegionId, selectedCityId, selectedDistrictId);
                        } else {
                            handleBoundaryUpdate();
                        }
                    });
            }

            function loadCities(regionId, selectedCityId = null, selectedDistrictId = null) {
                resetSelect(citySelect, '<option value="">{{ __('admin.select_option') }}</option>');
                resetSelect(districtSelect, '<option value="">{{ __('admin.select_option') }}</option>');

                if (!regionId) return;

                fetch(`{{ url('admin/locations/cities') }}/${regionId}`)
                    .then(response => response.json())
                    .then(data => {
                        populateSelect(citySelect, data.cities, selectedCityId);
                        if (selectedCityId) {
                            loadDistricts(selectedCityId, selectedDistrictId);
                        } else {
                            handleBoundaryUpdate();
                        }
                    });
            }

            function loadDistricts(cityId, selectedDistrictId = null) {
                resetSelect(districtSelect, '<option value="">{{ __('admin.select_option') }}</option>');
                if (!cityId) return;

                fetch(`{{ url('admin/locations/districts') }}/${cityId}`)
                    .then(response => response.json())
                    .then(data => {
                        populateSelect(districtSelect, data.districts, selectedDistrictId);
                        handleBoundaryUpdate();
                    });
            }

            countrySelect.addEventListener('change', function() {
                loadRegions(this.value);
                handleBoundaryUpdate();
            });

            regionSelect.addEventListener('change', function() {
                loadCities(this.value);

                const option = this.options[this.selectedIndex];
                if(option?.dataset.lat && option?.dataset.lng) {
                    flyToLocation(option.dataset.lat, option.dataset.lng, 9);
                }
                handleBoundaryUpdate();
            });

            citySelect.addEventListener('change', function() {
                loadDistricts(this.value);

                const option = this.options[this.selectedIndex];
                if(option?.dataset.lat && option?.dataset.lng) {
                    flyToLocation(option.dataset.lat, option.dataset.lng, 11);
                }
                handleBoundaryUpdate();
            });

            districtSelect.addEventListener('change', function() {
                const option = this.options[this.selectedIndex];
                if(option?.dataset.lat && option?.dataset.lng) {
                    flyToLocation(option.dataset.lat, option.dataset.lng, 13);
                }
                handleBoundaryUpdate();
            });

            // --- MAP INIT ---
            initLocationMap({
                elementId: 'map-container',
                entityLevel: 'project',
                entityId: {{ $project->id ?? 'null' }},
                // We use the input ID generated by x-location.map which is #boundary-{mapId}
                polygonFieldSelector: '#boundary-map-container',
                // Inputs generated by x-location.map
                latFieldSelector: '#lat-map-container',
                lngFieldSelector: '#lng-map-container',
                lat: {{ $project->lat ?? 26.8206 }}, // Default to Egypt center
                lng: {{ $project->lng ?? 30.8025 }},
                zoom: {{ $project->lat ? 13 : 6 }},
                lockToEgypt: false,
                onMapInit: function(map) {
                    mapInstance = map;
                    const selectedRegionId = regionSelect.dataset.selected;
                    const selectedCityId = citySelect.dataset.selected;
                    const selectedDistrictId = districtSelect.dataset.selected;
                    loadRegions(countrySelect.value, selectedRegionId, selectedCityId, selectedDistrictId);
                },
                onPolygonChange: function(data) {
                     if (data.features.length > 0) {
                         document.getElementById('boundary-map-container').value = JSON.stringify(data);
                     } else {
                         document.getElementById('boundary-map-container').value = '';
                     }
                }
            });
        });
    </script>
@endpush
@endsection
